# Generated by Django 4.2.7 on 2023-12-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_movies',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='movie.movie'),
        ),
    ]
